/* Generated By:JavaCC: Do not edit this line. AnalizadorLexicoConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AnalizadorLexicoConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LCORCHETE = 2;
  /** RegularExpression Id. */
  int RCORCHETE = 3;
  /** RegularExpression Id. */
  int LLLAVES = 4;
  /** RegularExpression Id. */
  int RLLAVES = 5;
  /** RegularExpression Id. */
  int LPAREN = 6;
  /** RegularExpression Id. */
  int RPAREN = 7;
  /** RegularExpression Id. */
  int DIGITOS = 8;
  /** RegularExpression Id. */
  int COMILLA = 9;
  /** RegularExpression Id. */
  int INDICADORES = 10;
  /** RegularExpression Id. */
  int FORMULAS = 11;
  /** RegularExpression Id. */
  int CUENTAS = 12;
  /** RegularExpression Id. */
  int ESPACIO = 13;
  /** RegularExpression Id. */
  int TABULACION = 14;
  /** RegularExpression Id. */
  int FORMATOFECHA = 15;
  /** RegularExpression Id. */
  int COMA = 16;
  /** RegularExpression Id. */
  int DOSPUNTOS = 17;
  /** RegularExpression Id. */
  int ID = 18;
  /** RegularExpression Id. */
  int OPERACION = 19;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "<DIGITOS>",
    "\"\\\"\"",
    "<INDICADORES>",
    "<FORMULAS>",
    "<CUENTAS>",
    "\" \"",
    "\"\\t\"",
    "<FORMATOFECHA>",
    "\",\"",
    "\":\"",
    "<ID>",
    "<OPERACION>",
  };

}
